// Shared translation strings
export const t = {
    en: {
        appName: 'Smart Panchayat',
        tagline: 'GramSeva Digital Services',
        navigation: 'Navigation',
        switchRole: 'Switch Role (Demo)',
        services: 'Services',
        complaints: 'Complaints',
        fileComplaint: 'File Complaint',
        trackComplaint: 'Track Complaint',
        pensionNav: 'Pension',
        certificatesNav: 'Certificates',
        taxNav: 'Tax Payments',
        accountSettings: 'Account Settings',
        supportCenter: 'Support Center',
        announcements: 'Announcements',
        dashboard: 'Dashboard',
        adminDashboard: 'Admin Dashboard',
        staffDashboard: 'Staff Dashboard',
        citizenDashboard: 'Citizen Dashboard',
        admin: 'Admin Panel',
        staff: 'Staff Portal',
        submit: 'Submit',
        cancel: 'Cancel',
        save: 'Save',
        search: 'Search...',
        logout: 'Logout',
        login: 'Login',
        register: 'Register',
        govtOfAp: 'Government of Andhra Pradesh',
        heroTitle: 'Your Panchayat. Your Voice. Digitized.',
        heroSub: 'File complaints, track resolutions, apply for pensions, pay taxes, and access all Gram Panchayat services — anytime, anywhere.',
        ourServices: 'Our Services',
        clickToStart: 'Click any service to get started',
        trackSub: 'Enter your complaint ID to check the current status',
        latestAnnouncements: 'Latest Announcements',
        viewAll: 'View All',
        helpline: 'Helpline: 1800-XXX-XXXX',
        rights: 'All rights reserved.',
        stats: {
            resolved: 'Complaints Resolved',
            rate: 'Resolution Rate',
            activePensions: 'Pensions Active',
            respTime: 'Avg Response Time',
        },
        roles: {
            citizen: 'Citizen',
            admin: 'Admin',
            staff: 'Staff',
        },
        status: {
            pending: 'Pending',
            inprogress: 'In Progress',
            resolved: 'Resolved',
            rejected: 'Rejected',
        },
        categories: {
            sanitation: 'Sanitation',
            streetlight: 'Street Light',
            water: 'Water Supply',
            road: 'Roads & Infrastructure',
            pension: 'Old Age Pension',
            health: 'Health',
            other: 'Other',
        },
        serviceNames: {
            sanitation: 'Sanitation',
            streetlight: 'Street Lights',
            pension: 'Old-Age Pension',
            water: 'Water Supply',
            certificates: 'Certificates',
            tax: 'Tax Payments',
            road: 'Roads',
            health: 'Health',
        },
        serviceDescs: {
            sanitation: 'Report garbage & drainage issues',
            streetlight: 'Report non-working light poles',
            pension: 'Apply or check pension status',
            water: 'Report water leakage or shortage',
            certificates: 'Income, caste, residence certs',
            tax: 'Pay house & water tax online',
            road: 'Report potholes, road damage & street issues',
            health: 'Health services & welfare schemes',
        },
        formLabels: {
            title: 'Title',
            description: 'Description',
            ward: 'Ward',
            priority: 'Priority',
            address: 'Location / Address',
            fullName: 'Full Name',
            mobile: 'Mobile Number',
            photo: 'Attach Photo',
            selectWard: 'Select Ward',
            priorityLow: 'Low',
            priorityMed: 'Medium',
            priorityHigh: 'High (Urgent)',
        },
        messages: {
            filedSuccess: 'Complaint Filed Successfully!',
            filedSub: 'Your complaint has been registered and will be reviewed within 24 hours.',
            saveId: 'Save this ID to track your complaint',
            detectingLoc: 'Detecting your location...',
            locCaptured: 'Location Captured!',
            useGps: 'Use My Current Location (GPS)',
            locMsg: 'You will receive SMS updates on the provided number regarding your complaint status.',
            reviewSubmit: 'Review & Submit',
        },
        steps: {
            category: 'Category',
            details: 'Details',
            contact: 'Contact',
            review: 'Review',
        },
        roles: {
            citizen: 'Citizen',
            admin: 'Admin',
            staff: 'Staff',
        },
        tax: {
            house: 'House Tax',
            water: 'Water Tax',
            trade: 'Trade License',
            houseDesc: 'Annual property tax for residential buildings',
            waterDesc: 'Monthly/quarterly water usage charges',
            tradeDesc: 'Annual trade license renewal fee',
            totalPaid: 'Total Paid (2023-24)',
            pendingTotal: 'Pending Amount',
            propertyId: 'Property ID',
            upToDate: 'Up to date',
            dueNow: 'Due now',
            records: 'Tax Records',
            confirmPay: 'Confirm Payment',
            payNow: 'Pay Now',
            fetching: 'Fetching your tax records...',
            noRecords: 'No Tax Records Found',
            noRecordsSub: 'It looks like there are no tax assessments linked to your email yet. Click below to generate a demo tax assessment for this year.',
            generateDemo: 'Generate Demo Taxes',
            receipt: 'Receipt',
            paymentSuccess: 'Payment successful!',
        },
        pensions: {
            title: 'Pension Management',
            sub: 'Apply for government pension schemes and track your application.',
            oldage: 'Old Age Pension',
            widow: 'Widow Pension',
            disability: 'Disability Pension',
            weaver: 'Weavers Pension',
            amountMsg: '₹{amt}/month',
            applyNow: 'Apply Now',
            activeRecords: 'Active Pension Records',
            applyFor: 'Apply for Pension',
            applySub: 'Select a pension type above to begin your application.',
            filedSuccess: 'Application Submitted!',
            filedSub: 'Your pension application will be reviewed within 7-10 working days.',
            appNum: 'Application Number',
            back: 'Back to Pensions',
            fillDetails: 'Fill in your details below',
            age: 'Age',
            aadhaar: 'Aadhaar Number',
            income: 'Annual Family Income',
            aadhaarPlaceholder: '12-digit Aadhaar',
            incomePlaceholder: 'e.g. ₹50,000',
        },
        certificates: {
            title: 'Certificate Services',
            sub: 'Apply for government certificates online. Fast, paperless, and free.',
            income: 'Income Certificate',
            caste: 'Caste Certificate',
            residence: 'Residence Certificate',
            birth: 'Birth Certificate',
            death: 'Death Certificate',
            noobj: 'No Objection Certificate',
            incomeDesc: 'Proof of family/individual income',
            casteDesc: 'OBC / SC / ST caste proof',
            residenceDesc: 'Proof of domicile / address',
            birthDesc: 'Birth registration proof',
            deathDesc: 'Death registration proof',
            noobjDesc: 'NOC for various purposes',
            feeTitle: 'Fee',
            readyIn: 'Ready in',
            days: '{d} days',
            free: 'Free',
            myCerts: 'My Certificates',
            selectType: 'Select a Certificate Type',
            selectSub: 'Click any certificate type above to apply.',
            fatherName: "Father's / Husband's Name",
            dob: 'Date of Birth',
            purpose: 'Purpose',
            purposePlaceholder: 'e.g. Bank loan, School admission',
            applyAnother: 'Apply for Another',
            download: 'Download',
        },
        tracking: {
            title: 'Track Your Complaint',
            sub: 'Enter your Complaint ID to get real-time status updates.',
            complaintId: 'Complaint ID',
            hint: 'Try:',
            search: 'Search',
            notFound: 'Complaint Not Found',
            checkId: 'Please check the ID and try again.',
            resolutionProgress: 'Resolution Progress',
            activityTimeline: 'Activity Timeline',
            resultsFor: 'Results for "{q}"',
            allComplaints: 'All Registered Complaints',
        },
        common: {
            progress: 'Progress',
            priority: 'Priority',
            high: 'High',
            medium: 'Medium',
            low: 'Low',
            ward: 'Ward',
            date: 'Date',
            assigned: 'Assigned',
            meeting: 'Meeting',
            notice: 'Notice',
            welfare: 'Welfare',
            infrastructure: 'Infrastructure',
        }
    },
    te: {
        appName: 'స్మార్ట్ పంచాయతీ',
        tagline: 'గ్రామసేవ డిజిటల్ సేవలు',
        navigation: 'నేవిగేషన్',
        switchRole: 'రోల్ మార్చండి (డెమో)',
        services: 'సేవలు',
        complaints: 'ఫిర్యాదులు',
        fileComplaint: 'ఫిర్యాదు నమోదు',
        trackComplaint: 'ఫిర్యాదు ట్రాక్',
        pensionNav: 'పింఛను',
        certificatesNav: 'సర్టిఫికేట్లు',
        taxNav: 'పన్ను చెల్లింపు',
        announcements: 'ప్రకటనలు',
        dashboard: 'డ్యాష్‌బోర్డ్',
        adminDashboard: 'అడ్మిన్ డ్యాష్‌బోర్డ్',
        staffDashboard: 'స్టాఫ్ డ్యాష్‌బోర్డ్',
        citizenDashboard: 'సిటిజన్ డ్యాష్‌బోర్డ్',
        admin: 'అడ్మిన్ ప్యానెల్',
        staff: 'స్టాఫ్ పోర్టల్',
        submit: 'సమర్పించు',
        cancel: 'రద్దు',
        save: 'సేవ్',
        search: 'వెతుకు...',
        logout: 'లాగ్ అవుట్',
        login: 'లాగిన్',
        register: 'నమోదు',
        govtOfAp: 'ఆంధ్రప్రదేశ్ ప్రభుత్వం',
        common: {
            progress: 'పురోగతి',
            priority: 'ప్రాధాన్యత',
            high: 'అధికం',
            medium: 'మధ్యమ',
            low: 'తక్కువ',
            ward: 'వార్డు',
            date: 'తేదీ',
            assigned: 'కేటాయించబడింది',
            meeting: 'సమావేశం',
            notice: 'నోటీసు',
            welfare: 'సంక్షేమం',
            infrastructure: 'మౌలిక సదుపాయాలు',
        },
        heroTitle: 'మీ పంచాయతీ. మీ గళం. డిజిటైజ్ అయింది.',
        heroSub: 'ఫిర్యాదులు నమోదు చేయండి, పరిష్కారాలు ట్రాక్ చేయండి, పింఛన్లకు దరఖాస్తు చేయండి, పన్నులు చెల్లించండి మరియి అన్ని గ్రామ పంచాయతీ సేవలను ఎప్పుడైనా, ఎక్కడైనా పొందండి.',
        ourServices: 'మా సేవలు',
        clickToStart: 'ప్రారంభించడానికి ఏదైనా సేవను క్లిక్ చేయండి',
        trackSub: 'ప్రస్తుత స్థితిని తనిఖీ చేయడానికి ఫిర్యాదు ID నమోదు చేయండి',
        latestAnnouncements: 'తాజా ప్రకటనలు',
        viewAll: 'అన్నీ చూడండి',
        helpline: 'హెల్ప్‌లైన్: 1800-XXX-XXXX',
        rights: 'అన్ని హక్కులు రిజర్వు చేయబడినవి.',
        stats: {
            resolved: 'పరిష్కరించిన ఫిర్యాదులు',
            rate: 'పరిష్కార రేటు',
            activePensions: 'చురుకైన పింఛన్లు',
            respTime: 'సగటు స్పందన సమయం',
        },
        formLabels: {
            title: 'శీర్షిక',
            description: 'వివరణ',
            ward: 'వార్డు',
            priority: 'ప్రాధాన్యత',
            address: 'స్థానం / చిరునామా',
            fullName: 'పూర్తి పేరు',
            mobile: 'మొబైల్ నంబర్',
            photo: 'ఫోటో జతచేయండి',
            selectWard: 'వార్డు ఎంచుకోండి',
            priorityLow: 'తక్కువ',
            priorityMed: 'మధ్యమ',
            priorityHigh: 'అధిక (అత్యవసరం)',
        },
        messages: {
            filedSuccess: 'ఫిర్యాదు విజయవంతంగా నమోదైంది!',
            filedSub: 'మీ ఫిర్యాదు నమోదు చేసుకుంది. 24 గంటలలో సమీక్షించబడుతుంది.',
            saveId: 'ఈ ID ని సేవ్ చేయండి',
            detectingLoc: 'మీ స్థానాన్ని గుర్తిస్తోంది...',
            locCaptured: 'స్థానాన్ని పొందింది!',
            useGps: 'నా ప్రస్తుత స్థానాన్ని ఉపయోగించండి (GPS)',
            locMsg: 'మీ ఫిర్యాదు స్థితి గురించి మీకు SMS నోటిఫికేషన్లు వస్తాయి.',
            reviewSubmit: 'సమీక్షించి సమర్పించండి',
        },
        steps: {
            category: 'వర్గం',
            details: 'వివరాలు',
            contact: 'సంప్రదింపు',
            review: 'సమీక్ష',
        },
        roles: {
            citizen: 'సిటిజన్',
            admin: 'అడ్మిన్',
            staff: 'స్టాఫ్',
        },
        tax: {
            house: 'ఇంటి పన్ను',
            water: 'నీటి పన్ను',
            trade: 'ట్రేడ్ లైసెన్స్',
            houseDesc: 'నివాస భవనాలకు వార్షిక ఆస్తి పన్ను',
            waterDesc: 'నెలవారీ/త్రైమాసిక నీటి వినియోగ ఛార్జీలు',
            tradeDesc: 'వార్షిక ట్రేడ్ లైసెన్స్ పునరుద్ధరణ రుసుము',
            totalPaid: 'మొత్తం చెల్లించినవి (2023-24)',
            pendingTotal: 'పెండింగ్ మొత్తం',
            propertyId: 'ఆస్తి ID',
            upToDate: 'అన్నీ సరిగ్గా ఉన్నాయి',
            dueNow: 'చెల్లించాల్సిన సమయం',
            records: 'పన్ను రికార్డులు',
            confirmPay: 'చెల్లింపు నిర్ధారించు',
            payNow: 'ఇప్పుడే చెల్లించు',
            fetching: 'మీ పన్ను రికార్డులను సేకరిస్తోంది...',
            noRecords: 'పన్ను రికార్డులు కనుగొనబడలేదు',
            noRecordsSub: 'మీ ఈమెయిల్ తో ఇప్పటివరకు పన్ను రికార్డులు లేవు. రికార్డులను సృష్టించడానికి క్రింద క్లిక్ చేయండి.',
            generateDemo: 'డెమో పన్నులను సృష్టించండి',
            receipt: 'రసీదు',
            paymentSuccess: 'చెల్లింపు విజయవంతమైంది!',
        },
        pensions: {
            title: 'పింఛన్ నిర్వహణ',
            sub: 'ప్రభుత్వ పింఛన్ పథకాలకు దరఖాస్తు చేసి మీ దరఖాస్తు ట్రాక్ చేయండి.',
            oldage: 'వృద్ధాప్య పింఛను',
            widow: 'విధవ పింఛను',
            disability: 'వికలాంగుల పింఛను',
            weaver: 'చేనేత కార్మికుల పింఛను',
            amountMsg: 'నెలకు ₹{amt}',
            applyNow: 'ఇప్పుడే దరఖాస్తు',
            activeRecords: 'చురుకైన పింఛన్ రికార్డులు',
            applyFor: 'పింఛన్ కు దరఖాస్తు',
            applySub: 'దరఖాస్తు ప్రారంభించడానికి పైన ఒక పింఛన్ రకం ఎంచుకోండి.',
            filedSuccess: 'దరఖాస్తు సమర్పించబడింది!',
            filedSub: 'మీ పింఛన్ దరఖాస్తు 7-10 పని దినాలలో సమీక్షించబడుతుంది.',
            appNum: 'దరఖాస్తు సంఖ్య',
            back: 'పింఛన్లకు వెనుకకు',
            fillDetails: 'మీ వివరాలు నమోదు చేయండి',
            age: 'వయసు',
            aadhaar: 'ఆధార్ నంబర్',
            income: 'వార్షిక కుటుంబ ఆదాయం',
            aadhaarPlaceholder: '12-అంకెల ఆధార్',
            incomePlaceholder: 'ఉదా: ₹50,000',
        },
        certificates: {
            title: 'సర్టిఫికేట్ సేవలు',
            sub: 'ఆన్‌లైన్‌లో ప్రభుత్వ సర్టిఫికేట్లకు దరఖాస్తు చేయండి. వేగంగా, పేపర్‌లెస్ మరియు ఉచితం.',
            income: 'ఆదాయ ధృవీకరణ పత్రం',
            caste: 'కుల ధృవీకరణ పత్రం',
            residence: 'నివాస ధృవీకరణ పత్రం',
            birth: 'జనన ధృవీకరణ పత్రం',
            death: 'మరణ ధృవీకరణ పత్రం',
            noobj: 'నిరాక్షేపణ పత్రం (NOC)',
            incomeDesc: 'కుటుంబ/వ్యక్తిగత ఆదాయ నిరూపణ',
            casteDesc: 'OBC / SC / ST కుల నిరూపణ',
            residenceDesc: 'స్థానిక నివాస/చిరునామా నిరూపణ',
            birthDesc: 'జనన నమోదు నిరూపణ',
            deathDesc: 'మరణ నమోదు నిరూపణ',
            noobjDesc: 'వివిధ అవసరాల కోసం NOC',
            feeTitle: 'రుసుము',
            readyIn: 'సిద్ధం కావడానికి',
            days: '{d} రోజులు',
            free: 'ఉచితం',
            myCerts: 'నా సర్టిఫికేట్లు',
            selectType: 'సర్టిఫికేట్ రకం ఎంచుకోండి',
            selectSub: 'దరఖాస్తు చేయడానికి పైన ఏదైనా సర్టిఫికేట్ రకంపై క్లిక్ చేయండి.',
            fatherName: 'తండ్రి / భర్త పేరు',
            dob: 'పుట్టిన తేదీ',
            purpose: 'ఉద్దేశం',
            purposePlaceholder: 'ఉదా: బ్యాంక్ రుణం, పాఠశాల ప్రవేశం',
            applyAnother: 'మరొకదానికి దరఖాస్తు',
            download: 'డౌన్‌లోడ్',
        },
        tracking: {
            title: 'ఫిర్యాదు ట్రాక్ చేయండి',
            sub: 'రియల్-టైమ్ స్టేటస్ అప్‌డేట్‌లు పొందడానికి మీ ఫిర్యాదు ID నమోదు చేయండి.',
            complaintId: 'ఫిర్యాదు ID',
            hint: 'ఉదాహరణ:',
            search: 'వెతుకు',
            notFound: 'ఫిర్యాదు కనుగొనలేదు',
            checkId: 'దయచేసి ID ని తనిఖీ చేసి తిరిగి ప్రయత్నించండి.',
            resolutionProgress: 'పరిష్కార పురోగతి',
            activityTimeline: 'కార్యకలాప టైమ్‌లైన్',
            resultsFor: '"{q}" కోసం ఫలితాలు',
            allComplaints: 'అన్ని రిజిస్టర్డ్ ఫిర్యాదులు',
        },
        status: {
            pending: 'పెండింగ్',
            inprogress: 'పురోగతిలో',
            resolved: 'పరిష్కరించబడింది',
            rejected: 'తిరస్కరించబడింది',
        },
        categories: {
            sanitation: 'పారిశుద్ధ్యం',
            streetlight: 'వీధి దీపాలు',
            water: 'నీటి సరఫరా',
            road: 'రోడ్లు',
            pension: 'వృద్ధాప్య పింఛను',
            health: 'ఆరోగ్యం',
            other: 'ఇతర',
        },
        serviceNames: {
            sanitation: 'పారిశుద్ధ్యం',
            streetlight: 'వీధి దీపాలు',
            pension: 'వృద్ధాప్య పింఛను',
            water: 'నీటి సరఫరా',
            certificates: 'సర్టిఫికేట్లు',
            tax: 'పన్ను చెల్లింపులు',
            road: 'రోడ్లు',
            health: 'ఆరోగ్యం',
        },
        serviceDescs: {
            sanitation: 'చెత్త & డ్రైనేజీ సమస్యల నివేదిక',
            streetlight: 'పని చేయని వీధి దీపాల నివేదిక',
            pension: 'పింఛను దరఖాస్తు లేదా స్థితి',
            water: 'నీటి లీకేజీ లేదా కొరత నివేదిక',
            certificates: 'ఆదాయ, కుల, నివాస ధృవీకరణ పత్రాలు',
            tax: 'ఇంటి & నీటి పన్ను ఆన్‌లైన్ చెల్లింపు',
            road: 'గోతులు & రోడ్డు దెబ్బతినడం నివేదిక',
            health: 'ఆరోగ్య సేవలు & సంక్షేమ పథకాలు',
        }
    },
};

// Sample data for initial dynamic display (Fallback if backend empty)
export const sampleComplaints = [
    {
        id: 'GS-2024-001',
        title: 'Street light not working near Rajiv Gandhi Colony',
        category: 'streetlight',
        status: 'inprogress',
        date: '2024-01-15',
        ward: 'Ward 3',
        priority: 'high',
        progress: 60,
    },
];

export const staffMembers = [
    { id: 'S1', name: 'Ravi Kumar', role: 'Electrician', dept: 'Electricity' },
    { id: 'S2', name: 'Suresh Reddy', role: 'Field Officer', dept: 'General' },
    { id: 'S3', name: 'Naveen Raj', role: 'Sanitation Lead', dept: 'Sanitation' },
    { id: 'S4', name: 'Gopal Rao', role: 'Plumber', dept: 'Water Supply' },
    { id: 'S5', name: 'Vikram Rao', role: 'Road Inspector', dept: 'Infrastructure' },
    { id: 'S6', name: 'Lakshmi Devi', role: 'Health Inspector', dept: 'Health' },
];

export const announcements = [
    {
        id: 1,
        icon: 'campaign',
        title: { en: 'Gram Sabha Meeting – Feb 28', te: 'గ్రామ సభ సమావేశం - ఫిబ్రవరి 28' },
        date: 'Feb 20, 2024',
        body: { en: 'All villagers are requested to attend...', te: 'గ్రామస్తులందరూ హాజరు కావాలి...' },
        category: 'Meeting',
    },
];

export const statusColor = {
    pending: 'badge-warning',
    inprogress: 'badge-info',
    resolved: 'badge-success',
    rejected: 'badge-danger',
};

export const categoryIcon = {
    sanitation: 'delete',
    streetlight: 'lightbulb',
    water: 'water_drop',
    road: 'add_road',
    pension: 'elderly',
    health: 'medical_services',
    other: 'assignment',
};

// Legacy alias
export const categoryEmoji = categoryIcon;
